
services:
  mongobd:
    image: mongo
    container_name: smokedetection-mongodb
    ports: 
      - "27017:27017"
    networks:
      - mynetwork
  grpcservice:
    image: grpc-service
    container_name: grpc-service
    ports:
      - "5138:8080"
    environment:
      ASPNETCORE_URLS: "http://+:80"
    depends_on:
      - mongobd
    networks:
      - mynetwork
  
  restservice:
    image: rest-service
    container_name: rest-service
    ports:
      - "5000:5000"
    depends_on:
      - mongobd
    networks:
      - mynetwork
  
networks:
  mynetwork:
    driver: bridge

version: '3.8'
